services:
    nginx:
        image: nginx:latest
        container_name: dashboard
        restart: always
        ports:
            - "80:80"  # Internal port, only accessible by Varnish
#            - "443:443"  # Optional HTTPS
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/html:/usr/share/nginx/html:ro
            - ./nginx/logs:/var/log/nginx
            - ./nginx/certs:/etc/nginx/certs:ro
        networks:
            - videonet_network
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - WEBUI_PORT=8081
        volumes:
            - ./:/config
            - ./qbittorrent/downloads:/downloads
        cpu_shares: 1024  # higher CPU priority (default is 512)
        deploy:
            resources:
                limits:
                  cpus: "2.0"      # Limits to 2 CPU cores
                  memory: "2G"     # Limits to 2GB RAM
                reservations:
                  cpus: "1.5"      # Reserves 1.5 CPU cores at minimum
                  memory: "1G"     # Reserves 1GB RAM at minimum
        networks:
            - videonet_network
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        restart: unless-stopped
        ports:
            - "8191:8191"
        environment:
            - LOG_LEVEL=info
            - CAPTCHA_SOLVER=none
        networks:
            - videonet_network
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        restart: unless-stopped
        ports:
            - "9696:9696"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./prowlarr/config:/config
        networks:
            - videonet_network
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        restart: unless-stopped
        ports:
            - "8989:8989"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./sonarr/config:/config
            - ./sonarr/tv:/tv
            - ./qbittorrent/downloads/sonarr:/downloads/sonarr
        networks:
            - videonet_network
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        restart: unless-stopped
        ports:
            - "7878:7878"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./radarr/config:/config
            - ./radarr/movies:/movies
            - ./qbittorrent/downloads/radarr:/downloads/radarr
        networks:
            - videonet_network
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        restart: unless-stopped
        ports:
            - "32400:32400"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - VERSION=docker
        volumes:
            - ./plex/config:/config
            - ./plex/transcode:/transcode
        networks:
            - videonet_network
    petio:
        image: ghcr.io/petio-team/petio:latest
        container_name: petio
        restart: unless-stopped
        ports:
            - "7777:7777"
        environment:
            - TZ=Etc/UTC
            - MONGO_URL=mongodb://mongodb:27017/
        volumes:
            - ./petio/config:/app/config
            - ./petio/logs:/app/logs
        depends_on:
            - plex
        networks:
            - videonet_network
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        ports:
          - "8096:8096"
#          - "8920:8920"  # HTTPS
        volumes:
          - ./jellyfin/config:/config
          - ./jellyfin/cache:/cache
          - ./sonarr/tv:/media/tv
          - ./radarr/movies:/media/movies
        environment:
          - TZ=Etc/UTC
          - JELLYFIN_PublishedServerUrl=http://localhost:8096
        networks:
          - videonet_network
networks:
    videonet_network:
        driver: bridge